### ISSUE TITLE
Training error on waymo 4-frame exp.

### ISSUE THREAD

**Issue by synsin0** [Eaphan/STEMD#2]
I use the default settings and 8 A100s to train 4-frame config. The log looks like
[log.txt](https://github.com/Eaphan/STEMD/files/14122510/log.txt). But error suddenly occurs like the follows. Any idea on why? 

k8s-job-9pr7b9-1706774363531-kwbz8:558:623 [0] NCCL INFO [Service thread] Connection closed by localRank 0
k8s-job-9pr7b9-1706774363531-kwbz8:558:558 [0] NCCL INFO comm 0x4d150de0 rank 0 nranks 8 cudaDev 0 busId 51000 - Abort COMPLETE
Traceback (most recent call last):
  File "/home/luban/miniconda3/envs/2080ti_torch113/bin/efg_run", line 33, in 
    sys.exit(load_entry_point('efg', 'console_scripts', 'efg_run')())
  File "/nfs/volume-904-5/shiyining_i/STEMD/cli/main.py", line 133, in main
    launcher(
  File "/nfs/volume-904-5/shiyining_i/STEMD/efg/engine/launch.py", line 52, in launch
    mp.spawn(
  File "/home/luban/miniconda3/envs/2080ti_torch113/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/luban/miniconda3/envs/2080ti_torch113/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/luban/miniconda3/envs/2080ti_torch113/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/luban/miniconda3/envs/2080ti_torch113/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/nfs/volume-904-5/shiyining_i/STEMD/efg/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/nfs/volume-904-5/shiyining_i/STEMD/cli/main.py", line 105, in worker
    trainer.train()
  File "/nfs/volume-904-5/shiyining_i/STEMD/efg/engine/trainer.py", line 67, in train
    self.step()
  File "/nfs/volume-904-5/shiyining_i/STEMD/playground/detection.3d/waymo/stemd/STEMD.waymo.resnet18.cdn.epoch12/./env.py", line 27, in step
    super().step()
  File "/nfs/volume-904-5/shiyining_i/STEMD/efg/engine/trainer.py", line 305, in step
    self._write_metrics(loss_dict, misc_dict)
  File "/nfs/volume-904-5/shiyining_i/STEMD/efg/engine/trainer.py", line 125, in _write_metrics
    metrics_dict = {k: np.mean([x[k] for x in all_metrics_dict]) for k in all_metrics_dict[0].keys()}
  File "/nfs/volume-904-5/shiyining_i/STEMD/efg/engine/trainer.py", line 125, in 
    metrics_dict = {k: np.mean([x[k] for x in all_metrics_dict]) for k in all_metrics_dict[0].keys()}
  File "/nfs/volume-904-5/shiyining_i/STEMD/efg/engine/trainer.py", line 125, in 
    metrics_dict = {k: np.mean([x[k] for x in all_metrics_dict]) for k in all_metrics_dict[0].keys()}
KeyError: 'loss_bbox_dn_0_dec_t0'

**Comment by Eaphan** [comment]
Thanks for your interest in our work. You can try the ad-hoc fix with:
`metrics_dict = {k: np.mean([x[k] for x in all_metrics_dict if k in x]) for k in all_metrics_dict[0].keys()}`
